ci: let the check run all but in the end check any fail

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -38,18 +38,28 @@ jobs:
         run: go mod download
 
       - uses: golangci/golangci-lint-action@v8
+        continue-on-error: true
 
       - name: Check format
         run: gofmt -l .
+        continue-on-error: true
 
       - name: Unit Test
         run: just test -coverprofile=coverage.txt
+        continue-on-error: true
 
       - name: Upload results to Codecov
         uses: codecov/codecov-action@v5
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           slug: ${{ github.repository }}
+        continue-on-error: true
+
+      - name: Fail if any previous step failed
+        if: ${{ failure() }}
+        run: |
+          echo "One or more steps failed."
+          exit 1
 
   sonar:
     name: SonarQube
